name: pysegcnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - xarray
  - gdal>=3.2
  - rasterio
  - netcdf4
  - h5py
  - h5netdf
  - matplotlib
  - seaborn
  - ipython

